language: go

notifications:
    email:
        on_success: change
        on_failure: always

git:
    depth: 1

env:
    - GO111MODULE=on

before_install:
   - GO_PKGS=$(go list ./... | grep -v /test-fixtures/)
   - echo $GO_PKGS
   - go install -v golang.org/x/lint/golint
   - go install -v honnef.co/go/tools/cmd/megacheck
   - go install -v github.com/mdempsky/unconvert
   - go install -v github.com/mdempsky/maligned

install: true

matrix:
    allow_failures:
        - go: tip
    fast_finish: true
    include:
        - go: 1.10.x
          script:
            - golint -set_exit_status $GO_PKGS
            - megacheck $GO_PKGS
            - unconvert $GO_PKGS
            - maligned $GO_PKGS
            - go test -race -v $GO_PKGS
        - go: 1.11.x
          script:
            - golint -set_exit_status $GO_PKGS
            - megacheck $GO_PKGS
            - unconvert $GO_PKGS
            - maligned $GO_PKGS
            - go test -race -v -mod=vendor $GO_PKGS
            - go test -race -v $GO_PKGS
        - go: 1.12.x
          script:
            - golint -set_exit_status $GO_PKGS
            - megacheck $GO_PKGS
            - unconvert $GO_PKGS
            - maligned $GO_PKGS
            - go test -race -v -mod=vendor $GO_PKGS
            - go test -race -v $GO_PKGS
        - go: tip
          script:
            - golint -set_exit_status $GO_PKGS
            - megacheck $GO_PKGS
            - unconvert $GO_PKGS
            - maligned $GO_PKGS
            - go test -race -v -mod=vendor $GO_PKGS
            - go test -race -v $GO_PKGS
